name: Remove copyright
on:
  schedule:
    - cron: '00 05 02 10 *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd problemsets
          cd aime
          rm -rf 2015
          rm -rf 2016
          rm -rf 2017
          rm -rf 2018
          rm -rf 2019
          rm -rf 2020
          rm -rf 2021
          cd ../amc12
          rm -rf 2015
          rm -rf 2016
          rm -rf 2017
          rm -rf 2018
          rm -rf 2019
          rm -rf 2020
          rm -rf 2021
          cd ../amc10
          rm -rf 2015
          rm -rf 2016
          rm -rf 2017
          rm -rf 2018
          rm -rf 2019
          rm -rf 2020
          rm -rf 2021
          cd ../amc8
          rm -rf 2014
          rm -rf 2015
          rm -rf 2016
          rm -rf 2017
          rm -rf 2018
          rm -rf 2019
          rm -rf 2020
          cd ../../
          git config user.name bkf2020
          git config user.email bkf2020@users.noreply.github.com
          git add .
          git commit -m "Remove copyright"
          git push
      - run: echo "This job's status is ${{ job.status }}."
