name: Update Problemsets Daily
on: 
  schedule:
    - cron: '0 22 * * *'
jobs:
  Update-Problemsets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job runs everyday at 22:00 UTC"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             pip install bs4
      - name: Updating problemsets with update.py
        run: |
             python3 ${{ github.workspace }}/.github/workflows/update.py
      - run: echo "This job's status is ${{ job.status }}."
